const inquirer = require('inquirer');
const fs = require('fs');

function writeReadMe() {
    inquirer
    .prompt([
        { 
            type: "input",
            name: "fullName",
            message: "What is your full name?",
        },
        { 
            type: "input",
            name: "email",
            message: "What is your email address?",
        },
        { 
            type: "input",
            name: "gitHub",
            message: "What is your GitHub username?",
        },
       { 
        type: "input",
        name: "title",
        message: "What is your project title?",
       },
       { type: 'input',
        name: 'description',
        message: 'Enter the description.',
       },
       { type: 'input',
        name: 'installation',
        message: 'What are the steps required to install your project?',
       },
       { type: 'input',
        name: 'usage',
        message: 'Provide instructions and examples for use.',
       },
       { type: 'input',
        name: 'credits',
        message: 'List your collaborators, if any, with links to their GitHub profiles.',
       },
       { type: 'input',
        name: 'contributing',
        message: 'Add guidelines for for other developers who contribute.',
       },
       { type: 'input',
        name: 'tests',
        message: 'Write tests for your application.',
       },
        { type: 'list',
        name: 'license',
        message: 'Select a license to use.',
        choices: [
            {
              key: 'M',
              name: 'MIT',
              value: `MIT License

https://opensource.org/licenses/MIT

![MIT Badge](https://img.shields.io/badge/license-MIT-blue)

Copyright (c) 2023 [Full Name]
              
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
              
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
              
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`,
            },
            {
              key: 'U',
              name: 'Boost',
              value: `Boost Software License - Version 1.0 - August 17th, 2003

https://www.boost.org/LICENSE_1_0.txt 

[![License](https://img.shields.io/badge/License-Boost_1.0-lightblue.svg)]

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:
              
The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.
              
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.`,
            },
            {
              key: 'd',
              name: 'Unlicense',
              value: `This is free and unencumbered software released into the public domain.

http://unlicense.org/

![License: Unlicense](https://img.shields.io/badge/license-Unlicense-blue.svg)

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.
              
In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.
              
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
              
For more information, please refer to <https://unlicense.org>`,
            },
            {
                key: 'N',
                name: 'None',
                value: ``,
              },
          ],
       },
    ])
    .then ((answer) => {


        var readMe = (
`# ${answer.title}

 ## Description 
        
${answer.description}
        
 ## Table of Contents

* [Installation](#installation)
* [Usage](#usage)
* [Credits](#credits)
* [License](#license)
* [Contributing](#contributing)
* [Tests](#tests)
        
## Installation
        
${answer.installation}
        
## Usage 
        
${answer.usage}
        
## Credits
        
${answer.credits}
        
## License
        
${answer.license}

## Contributing
        
${answer.contributing}

## Tests
        
${answer.tests}

## Questions

For any furthur questions, please contact ${answer.fullName} at ${answer.email}. 
GitHub Profile: https://api.github.com/users/${answer.gitHub}/repos?per_page=100

© 2022 Trilogy Education Services, LLC, a 2U, Inc. brand. Confidential and Proprietary. All Rights Reserved.`)

   fs.writeFile('templateREADME.md', readMe, (err) => {
    if (err) throw err;
    console.log('templateREADME.md created');
   })
    })

}


writeReadMe();